"""Application-wide configuration defaults."""

from __future__ import annotations

DEFAULT_VISION_MODEL = "gpt-5.6-terra"
DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1"
DEFAULT_OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
DEFAULT_OPENAI_IMAGE_DETAIL = "original"
DEFAULT_OPENAI_REASONING_EFFORT = "none"
DEFAULT_ANALYSIS_INTERVAL_SEC = 15.0
DEFAULT_OCR_INTERVAL_SEC = 120.0
DEFAULT_MAX_FRAME_WIDTH = 1280
