"""Application-wide configuration defaults."""

from __future__ import annotations

DEFAULT_VISION_MODEL = "qwen3-vl:4b"
DEFAULT_OLLAMA_URL = "http://127.0.0.1:11435"
DEFAULT_OLLAMA_NUM_CTX = 4096
DEFAULT_OLLAMA_KEEP_ALIVE = "5m"
DEFAULT_ANALYSIS_INTERVAL_SEC = 15.0
DEFAULT_OCR_INTERVAL_SEC = 120.0
DEFAULT_MAX_FRAME_WIDTH = 1280
