"""Application-wide configuration defaults."""

from __future__ import annotations

DEFAULT_VISION_MODEL = "qwen3-vl:8b"
DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_ANALYSIS_INTERVAL_SEC = 30.0
DEFAULT_OCR_INTERVAL_SEC = 120.0
DEFAULT_MAX_FRAME_WIDTH = 768
DEFAULT_OLLAMA_NUM_CTX = 4096
DEFAULT_OLLAMA_TEMPERATURE = 0.0
